#include "process.h"
#include <windows.h>
#include <WindowsX.h>
#include <commctrl.h>
#include <io.h>
#include <map>
#include "math.h"
#include "pxcvideomodule.h"
#include "pxcmetadata.h"
#include "service/pxcsessionservice.h"
#include <pxcsensemanager.h>  
#include <pxcsession.h>
#include <utilities\pxcsmoother.h>
#include "util_render.h" 
#include <iostream>
#include <stdio.h> 
#include <opencv2/opencv.hpp>  
#include <string.h>

